### ISSUE TITLE
Sample.js not working

### ISSUE THREAD

**Issue by Apollon77** [NorthernMan54/Hap-Node-Client#55]
Reasons:
* debug lib is included hard from ../node_modules
* mdns_resolver is not a dep (and also required hard from ../node_modules

**Comment by Apollon77** [comment]
I was searching for a way to interact with "home bridges" devices directly ... but then I noticed that your lib only focus on homebridge as server ... I more look for "all other then homebridge" ...

**Comment by NorthernMan54** [comment]
Maybe I’m misunderstanding your use case, but I made this package to manage the interactions with my homebridge accessories, utilizing the HAP interface from homebridge.  So I could discover, receive status updates and control my homebridge devices for Alexa and node-red integration packages.

there is a another package floating around for HomeKit directly.

**Comment by Apollon77** [comment]
For Homekit directl yI found https://github.com/forty2/hap-client (or better a fork with updated deps and try to fix the bugs there right now ... lets see where it leads me to :-)

**Comment by NorthernMan54** [comment]
Good luck sir

**Comment by Apollon77** [comment]
Thank you. But one qestion you might be able to answer: Are Bridges also "pushing" infos out? Or is anything "get"?

I was able with the other library to connect to my hue bridge and read out characteristics, services and values ... but all only on "get" ... is there no events or "Push"?

**Comment by NorthernMan54** [comment]
Have you read the HomeKit accessory protocol documentation from apple, it documents the HomeKit event model, which is based on registering for events, and the event/push messages.  My library supports this, and I believe hap-client does as well.

**Comment by Apollon77** [comment]
Which "call" is it for registering? ANd no I need to read that (seems I need to got that deep :-)) )

**Comment by Apollon77** [comment]
PS: Read now and now I giot it ... seems I need to do another call :-)
