### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by lstrojny** [NorthernMan54/Hap-Node-Client#57]
Any plans to publish a new release to npm. I use your library within but I use a git hash version now since I need the latest changes (where the "name" attribute is now included in the server info) but those are not yet published on npm. Also, thank you for the library!

**Comment by NorthernMan54** [comment]
Tks for the nudge, I just published it

https://www.npmjs.com/package/hap-node-client/v/0.1.23

**Comment by lstrojny** [comment]
Awesome, thanks man! Just so you know, three new versions have been published (0.1.23, 0.1.24 and 0.1.25). No harm though, I just use the latest.

**Comment by NorthernMan54** [comment]
I have a bash script I have used for years to publish, but it keeps failing when it gets to the GitHub portion ( the recent 2FA ), so I have been running it a few times in a row to see what's wrong.

Their may be a few more ;-(
